/**
 * Generated by `scripts/generate-sdk-manifest.mjs` — do not edit by hand.
 *
 * Describes the real SDK projects in `sdk-source/` that the download endpoint
 * packages on demand. `sha256` is a digest of the source tree, so it changes
 * whenever any SDK file changes.
 */

export type SdkArchiveInfo = {
  /** Number of files in the packaged project. */
  files: number;
  /** Total uncompressed size of the source tree, in bytes. */
  bytes: number;
  /** SHA-256 digest of the source tree. */
  sha256: string;
};

export const SDK_ARCHIVES: Record<string, SdkArchiveInfo> = {
  "c": {
    "files": 7,
    "bytes": 24255,
    "sha256": "dbff5a4d5cd890421595cb4be64f0d58a69cade13acf30fe7af104a9201bf772"
  },
  "cpp": {
    "files": 7,
    "bytes": 30062,
    "sha256": "9212b70a5a258b6bb5d70f9d817de2fca722c229f18e5e2e5c3578b1750003ac"
  },
  "csharp": {
    "files": 6,
    "bytes": 45423,
    "sha256": "3473c84152ffbd089946778e55c6643b4654a0cd3ec97c8c523cc3bea4eab55f"
  },
  "dart": {
    "files": 11,
    "bytes": 15211,
    "sha256": "cd75881b5241a011ef7b0956584b6f85243f3716e51354fbf9979d7197168b9a"
  },
  "go": {
    "files": 9,
    "bytes": 20519,
    "sha256": "d23c1376794597c3cea47f9c69a12039e09662f06fab3c3850390c60a1cb5a92"
  },
  "java": {
    "files": 10,
    "bytes": 26761,
    "sha256": "81f3d545b583fa74dfa011d40763a358ebde13e12def0672d599ed0368ae3981"
  },
  "javascript": {
    "files": 8,
    "bytes": 18452,
    "sha256": "3785155c31fc54fb7454ca1941db1be2e543bc70f989b89de9662c6592fd12a8"
  },
  "kotlin": {
    "files": 9,
    "bytes": 19041,
    "sha256": "32ec712d13dd979250cc4a2af1c3f02ebaf9a21690d0d6fb9145e9e9b6beb9be"
  },
  "lua": {
    "files": 7,
    "bytes": 15586,
    "sha256": "3f1e358fc7c9f382a8952dbf7214ec5071f248ba52b4959171f1ec28eb59e90d"
  },
  "objc": {
    "files": 11,
    "bytes": 25638,
    "sha256": "91670f1268171c6eec8a7b1a20f1ec4a01bb4f21a08021b134df59704c52b329"
  },
  "php": {
    "files": 7,
    "bytes": 13180,
    "sha256": "70410b7f6953fb7ded475f8c7a4d4fdf8a2964ba203c6b1ea6a5dbff5d8127a7"
  },
  "python": {
    "files": 8,
    "bytes": 50679,
    "sha256": "72d997c13a9f62cd87b57aec57317c997f04d8ee9fbfc10b5f9387684371fb07"
  },
  "rust": {
    "files": 9,
    "bytes": 21478,
    "sha256": "1406543c103b4aa5d1f0aa49e75e672f7fdafed216fd279ba3f4c573fd88f46c"
  },
  "swift": {
    "files": 9,
    "bytes": 16631,
    "sha256": "1c1355f823e1f7bd9ca7cc956116ca183ebf919eea2ef680b94a9bbe3df2d576"
  },
  "typescript": {
    "files": 11,
    "bytes": 18762,
    "sha256": "feffa57986d182a50cd2e0ff9986ae69353ef8666dabd7e25aeb4f03849e7bb2"
  }
};

/** Human-readable size for an SDK source tree. */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}
